<a href="https://colab.research.google.com/github/hrithikashukla/Sem6-NLP/blob/master/class%20assignment/Sentiment_textblob.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import re
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score

In [0]:
from textblob import TextBlob
import nltk
nltk.download('punkt')
nltk.download('vader_lexicon')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


True

In [0]:
twitter=pd.read_csv('https://raw.githubusercontent.com/zfz/twitter_corpus/master/full-corpus.csv',error_bad_lines=False)
amazon=pd.read_json("http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/reviews_Office_Products_5.json.gz",lines=True)
twitter=twitter[twitter['Sentiment']!='irrelevant']
twitter.head()

Topic  ...                                          TweetText
0  apple  ...  Now all @Apple has to do is get swype on the i...
1  apple  ...  @Apple will be adding more carrier support to ...
2  apple  ...  Hilarious @youtube video - guy does a duet wit...
3  apple  ...  @RIM you made it too easy for me to switch to ...
4  apple  ...  I just realized that the reason I got into twi...

[5 rows x 5 columns]

In [0]:
def sentiment_polarity(text):
  blob=TextBlob(text)
  for sentence in blob.sentences:
    score=(sentence.sentiment.polarity)
    if score > 0.0:
      return "positive"
    elif score < 0.0:
      return "negative"
    else:
      return "neutral"

In [0]:
twitter['Sentiment Blob']=twitter['TweetText'].apply(sentiment_polarity)
amazon['Sentiment Blob']=amazon['reviewText'].apply(sentiment_polarity)

In [0]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [0]:
def sent_intanalyzer(sentence):
  sia = SentimentIntensityAnalyzer()
  for text in sentence:
    polarity = sia.polarity_scores(text)
    if polarity['compound'] >= 0.05:
      return "positive"
    elif polarity['compound'] <= -0.05:
      return "negative"
    else:
      return "neutral"

In [0]:
twitter['Sentiment SIA']=twitter['TweetText'].apply(sent_intanalyzer)
amazon['Sentiment SIA']=amazon['reviewText'].apply(sent_intanalyzer)

In [0]:
tblob_cm=confusion_matrix(twitter['Sentiment'],twitter['Sentiment Blob'])
sia_cm=confusion_matrix(twitter['Sentiment'],twitter['Sentiment SIA'])
tblob_acc=accuracy_score(twitter['Sentiment'],twitter['Sentiment Blob'])
sia_acc=accuracy_score(twitter['Sentiment'],twitter['Sentiment SIA'])

In [0]:
print("Blob Confusion Matrix", tblob_cm)
print("_______________________________")
print("SIA Confusion Matrix", sia_cm)
print("_______________________________")
print("Blob Accuracy", tblob_acc)
print("_______________________________")
print("SIA Accuracy", sia_acc)

Blob Confusion Matrix [[ 178  260  134]
 [ 189 1339  805]
 [  34  195  290]]
_______________________________
SIA Confusion Matrix [[   0  572    0]
 [   0 2333    0]
 [   0  519    0]]
_______________________________
Blob Accuracy 0.5277453271028038
_______________________________
SIA Accuracy 0.6813668224299065
